name: create-doubtfire-deployment
on:
  push:
    tags:
      - 'v*'
  deployment:
  workflow_dispatch:
jobs:
  docker-webserver:
    environment: deployment-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Build local webserver container to generate web application
        uses: docker/build-push-action@v2
        with:
          context: ./doubtfire-web
          push: false
          load: true
          tags: doubtfire-web:local
      # - name: Build web application
      #   run: docker run -v ${{ github.workspace }}/doubtfire-web:/doubtfire-web -v ${{ github.workspace }}/doubtfire-web/dist:/doubtfire-web/dist --workdir /doubtfire-web doubtfire-web:local npm run-script deploy
      - name: Generate web application to doubtfire-web/dist
        uses: addnab/docker-run-action@v3
        with:
          image: doubtfire-web:local
          options: -v ${{ github.workspace }}/doubtfire-web:/doubtfire-web -v ${{ github.workspace }}/doubtfire-web/dist:/doubtfire-web/dist --workdir /doubtfire-web 
          run:  |
            echo "Running deploy script in local doubtfire-web"
            npm ci
            npm run-script deploy
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup meta for webserver
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: lmsdoubtfire/webserver
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and push webserver
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: webserver.Dockerfile
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  docker-pdfGen:
    environment: deployment-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup meta for pdfGen
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: lmsdoubtfire/pdfGen
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and push pdfgen
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: pdfgen.Dockerfile
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  docker-overseer:
    environment: deployment-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup meta for Overseer
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: lmsdoubtfire/overseer
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and push overseer
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: overseer.Dockerfile
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
